#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if [ -f "$SCRIPT_DIR/conjur_credentials.env" ]; then
  # shellcheck disable=SC1091
  source "$SCRIPT_DIR/conjur_credentials.env"
fi

required_vars=(
  CONJUR_APPLIANCE_URL
  CONJUR_ACCOUNT
  CONJUR_AUTHN_LOGIN
  CONJUR_AUTHN_API_KEY
)

for var_name in "${required_vars[@]}"; do
  if [ -z "${!var_name:-}" ]; then
    echo "ERROR: Missing required environment variable: $var_name"
    echo "Source ./conjur_credentials.env generated by workload provisioning."
    exit 1
  fi
done

echo "--- Variables Used ---"
echo "CONJUR_APPLIANCE_URL=$CONJUR_APPLIANCE_URL"
echo "CONJUR_ACCOUNT=$CONJUR_ACCOUNT"
echo "CONJUR_AUTHN_LOGIN=$CONJUR_AUTHN_LOGIN"

summon -p summon-conjur bash consumer.sh
