---
apiVersion: v1
kind: Namespace
metadata:
  name: hashi-vault

---
# Vault server public certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-tls
  namespace: hashi-vault
spec:
  secretName: vault-server-tls  # Must match the extraVolumes name above
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .VAULT_FQDN }} # Your real domain
  dnsNames:
    - {{ .VAULT_FQDN }}
