apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: conjur
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: conjur
    kind: SecretStore
  target:
    name: conjur-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: data/vault/k8s-eso/account-ssh-user-1/username
    - secretKey: password
      remoteRef:
        key: data/vault/k8s-eso/account-ssh-user-1/password
